name: Docker build and push
on:
  push:
    branches: 
      - main
jobs:
  build:
    uses: y13i/actions/.github/workflows/docker.yml@main
    secrets:
      dockerhub-access-token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
